baseURL: https://awasn.github.io/
languageCode: en-us
title: arkadiusz wasniewski blog

disqusShortname: awasn-github-io

params:
  urls:
    highlight: https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.14.2
  dateFormats:
    publishedOn: 2 January 2006 15:04 MST
    postMetadata: 02 January 2006 15:04 MST

blackfriday:
  hrefTargetBlank: true

author:
  name: Arkadiusz Waśniewski

taxonomies:
  category: categories
  series: series
  tag: tags

permalinks:
  blog: /:filename/

menu:
  main:
    - identifier: blog
      name: blog
      url: /blog/
      weight:  1
    - identifier: categories
      name: categories
      url: /categories/
      weight:  2
    - identifier: tags
      name: tags
      url: /tags/
      weight:  3
    - identifier: about
      name: about
      url: /about/
      weight: 4